Use numpy to generate array of 25 random numbers sampled from a standard normal distribution

In [1]:
import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[-0.03089849 -0.15049987 -0.47147652  0.787702    0.36788725  0.04747206
  1.19374738  0.02777891  0.54610515 -0.66298812  0.05567471 -1.04632736
  0.47586397 -1.51472826 -0.91192053 -0.27985045  1.0847431  -1.57653371
 -1.25996597 -0.72110586 -2.27273133  0.71813371  0.62897598  1.12398334
  0.80703546]


Create a random vector of size 30 and find the mean value.

In [2]:
a = np.random.random(30)
b = a.mean()
print(b)

0.44126391653831293


Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.

In [8]:
import numpy as np
Z = np.arange(100).reshape(10,10)
print(Z)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Create a 10x10 array with random values and find the minimum and maximum values.


In [17]:
import numpy as np
a=np.random.random(100)
print(a)
amin, amax = a.min(), a.max()
print("minimum:",amin, "maximum:",amax)

[0.59527657 0.58943653 0.97903534 0.04108347 0.07058234 0.81131545
 0.90498122 0.01072017 0.12786832 0.97159885 0.49372277 0.57212969
 0.53041965 0.05529873 0.977268   0.96350533 0.70816015 0.10643364
 0.46019007 0.09990453 0.13519773 0.67755639 0.13925151 0.85476298
 0.38835323 0.67882899 0.96686989 0.89321934 0.58313633 0.30873665
 0.85263457 0.21871769 0.31310089 0.8200225  0.72126657 0.78649049
 0.62007365 0.02141331 0.96272508 0.801255   0.02554103 0.85816909
 0.87021934 0.99408868 0.98106858 0.22617615 0.92724385 0.31858455
 0.13991819 0.40950812 0.42672508 0.89480034 0.5187197  0.67496491
 0.94445759 0.30295731 0.77310942 0.47967493 0.56513331 0.52207344
 0.08314675 0.22791882 0.0032199  0.88501969 0.20002453 0.48269345
 0.78213451 0.35811189 0.43625345 0.67909374 0.71637937 0.61509002
 0.79951632 0.1095833  0.33059269 0.86936613 0.39504869 0.58607092
 0.38843469 0.65492899 0.86629281 0.58964419 0.50733353 0.19968364
 0.19087249 0.98054084 0.66669432 0.40956806 0.82763606 0.1400

Find Dot product of two arrays

f = np.array([1,2])

g = np.array([4,5])

In [18]:
f = np.array([1,2])

g = np.array([4,5])
np.dot(f,g)

14

Concatenate following arrays along axis=0
Ans: x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

In [21]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

np.concatenate((x,y), axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6]])

#How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])





In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])

In [24]:
arr = np.array([10,5,8,4,7,2,3,1])
arr.sort()
print('Sorted Array : ', arr)

Sorted Array :  [ 1  2  3  4  5  7  8 10]
